import serial
ser = serial.Serial('/dev/ttyUSB0',baudrate=9600,bytesize=8,parity='N',stopbits=2, dsrdtr=True)
print(ser.name)
print(ser)
ser.write(b'*IDN?\n')
resp = ser.readline()
print(resp)
ser.write(b'SYST:REM\n')
#resp = ser.readline()
#print(resp)
ser.write(b'MEAS:VOLT:DC?\n')
resp = ser.readline()
voltage = float((resp.decode('utf-8')).rstrip())
print(voltage)
#ser.close()
